[package]
name = "backend"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
serde = { version = "1.0.217", features = ["derive"], default-features = false }
postcard = { version = "1.1.1", features = ["alloc"] }
tokio = { version = "1.43.0", features = ["full"] }