[package]
name = "backend"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
serde = { version = "1.0.214", features = ["derive"], default-features = false }
postcard = { version = "1.0.10", features = ["alloc"]}