[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
backend = { path = "../backend" }
serde = { version = "1.0.214", default-features = false }
postcard = { version = "1.0.10", features = ["alloc"] }
env_logger = "0.11.5"
log = "0.4.22"