version: '3.9'

services:
  backend:
    build:
      context: ./api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite://transactions.db
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: ./front
    ports:
      - "8080:80"